version: 0.0
os: linux

files:
  - source: /stock-manager.jar
    destination: /home/ec2-user/app
  - source: /scripts
    destination: /home/ec2-user/app/scripts

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/setup_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root